ui: tape
browsers:
  - name: chrome
    version: latest
    platform: Windows 10
  - name: safari
    version: latest
    platform: Windows 10
  - name: chrome
    version: latest
    platform: Mac 10.10
  - name: safari
    version: latest
    platform: Mac 10.10
  - name: ie
    version: latest
  - name: opera
    version: latest
browserify:
  - transform: require-globify
